spring:
  application:
    name: datamovie

  datasource:
    url: jdbc:postgresql://localhost:5432/datamovie
    username: postgres
    password: senha123
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true

springdoc:
  api-docs:
    path: /api/api-docs
  swagger-ui:
    path: /swagger/index.html

datamovie:
  security:
    secret: "malfeito-feito"